# Machine Learning Template Notebook
notebook template for ML project.
The purpose is to speed up the working flow with prepared cells.

In [191]:
# LIBRAIRIES
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder

In [2]:
# DATASET IMPORT
df = pd.read_csv('train.csv')

## 1. DATA ANALYSE
* check the size of the dataset (how many rows ? Columns ?), is it enough ? how many features ? ...
* check the data types of columns. Is there categorical values ? what are the columns names ? Are they relevant ? Waht is the label column name ?
* Show firsts and lasts rows. Do you understand all datas ? Is there empty cells ? Does it seems ok ?
* Show basics statistics. All columns have same numbers of data ? is there strange data ? (age min, max and mean...)
* Check empty cells. Is it logical ? What should you do with it ? What type of feature engenerring is best to apply ?

In [3]:
# Dataset dimensions
df.shape

(891, 12)

In [4]:
# Dataset types of data
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [5]:
# 5 first and last rows of the dataset
display(df.head())
display(df.tail())

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

_SibSp = frères / soeurs / époux.se onboard_

_Parch = parents / children onboard_

_Embarked = port of embarkment (Southampton, Queenstown, Cherbourg)_

In [6]:
# Some basic statistics
display(df.describe())
display(df.describe(include='object'))

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

Name   Sex  Ticket Cabin Embarked
count                         891   891     891   204      889
unique                        891     2     681   147        3
top     Harrington, Mr. Charles H  male  347082    G6        S
freq                            1   577       7     4      644

In [7]:
# Check empty cells by columns
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
# Check empty cells rows to determine what strategy.
df[df.Embarked.isnull()]

PassengerId  Survived  Pclass                                       Name  \
61            62         1       1                        Icard, Miss. Amelie   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket  Fare Cabin Embarked  
61   female  38.0      0      0  113572  80.0   B28      NaN  
829  female  62.0      0      0  113572  80.0   B28      NaN

Miss Amelie Icard board at Southampton on the ticket of Mrs George Nelson Stone. She was her maid.

In [15]:
# Check other rows with empty cells
df[df.Age.isnull()]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [23]:
# check the the empty cells by class passenger
for tclass in df.Pclass.unique():
    print('nombre de passager en classe', tclass, ':', len(df[df.Pclass == tclass]))
    print('nombre de cellules Age vide :', df[df.Pclass == tclass].Age.isnull().sum())

nombre de passager en classe 3 : 491
nombre de cellules Age vide : 136
nombre de passager en classe 1 : 216
nombre de cellules Age vide : 30
nombre de passager en classe 2 : 184
nombre de cellules Age vide : 11


In [25]:
# check if empty age are on same ticket as someone else
df[df.Ticket == '330877']

PassengerId  Survived  Pclass              Name   Sex  Age  SibSp  Parch  \
5            6         0       3  Moran, Mr. James  male  NaN      0      0   

   Ticket    Fare Cabin Embarked  
5  330877  8.4583   NaN        Q

In [26]:
# check for cabin or not by class
for tclass in df.Pclass.unique():
    print('nombre de passager en classe', tclass, ':', len(df[df.Pclass == tclass]))
    print('nombre de cellules Cabin vide :', df[df.Pclass == tclass].Cabin.isnull().sum())

nombre de passager en classe 3 : 491
nombre de cellules Cabin vide : 479
nombre de passager en classe 1 : 216
nombre de cellules Cabin vide : 40
nombre de passager en classe 2 : 184
nombre de cellules Cabin vide : 168


In [55]:
# check class and cabin
display(df[(df.Pclass == 3)].Cabin.unique())
display(df[(df.Pclass == 2)].Cabin.unique())
display(df[(df.Pclass == 1)].Cabin.unique())

array([nan, 'G6', 'F G73', 'F E69', 'E10', 'F G63', 'E121', 'F38'],
      dtype=object)

array([nan, 'D56', 'F33', 'E101', 'F2', 'F4', 'D', 'E77'], dtype=object)

array(['C85', 'C123', 'E46', 'C103', 'A6', 'C23 C25 C27', nan, 'B78',
       'D33', 'B30', 'C52', 'B28', 'C83', 'E31', 'A5', 'D10 D12', 'D26',
       'C110', 'B58 B60', 'D47', 'B86', 'C2', 'E33', 'B19', 'A7', 'C49',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'C22 C26', 'C106', 'C65', 'E36', 'C54', 'B57 B59 B63 B66',
       'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40', 'T', 'C128',
       'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E44', 'A34', 'C104',
       'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14', 'B37', 'C30',
       'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38', 'B39', 'B22',
       'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68', 'B41', 'A20',
       'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48', 'E58', 'C126',
       'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'C62 C64', 'E24', 'C90',
       'C45', 'E8', 'B101', 'D45', 'C46', 'D30', 'D11', 'B3', 'D6',
       'B8

In [56]:
# check the rows with cabin name 'T'
df[df.Cabin == 'T']

PassengerId  Survived  Pclass                          Name   Sex   Age  \
339          340         0       1  Blackwell, Mr. Stephen Weart  male  45.0   

     SibSp  Parch  Ticket  Fare Cabin Embarked  
339      0      0  113784  35.5     T        S

## 2. Data Cleaning

* Fill empty cells that can be

In [60]:
# add info on Embarked empty cells

# first copy the df on a new one
cleaned_df = df.copy()

# fill empty embarked cells
cleaned_df.Embarked.fillna('S', inplace=True)
cleaned_df.Embarked.isnull().sum()

0

In [186]:
# Drop empty cells or columns

# df.dropna() ou df.column_name.dropna()
cleaned_df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin', 'Embarked'], axis = 1, inplace = True)

## 3. feature engineering

In [94]:
# add column/feature with other column/feature

# Select an string element in column and add a column
cleaned_df['Deck'] = cleaned_df.Cabin.str[0]
cleaned_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked Deck  
0      0         A/5 21171   7.2500   NaN        S  NaN  
1      0          PC 17599  71.2833   C85        C    C  
2      0  STON/O2. 3101282   7.9250   NaN        S  NaN  
3      0            113803  53.1000  C123        S    C  
4      0            373450   8.0500   NaN        S  NaN

In [96]:
# add column with applying functions on other columns

# is there orphan ?
df[(df.Parch == 0) & (df.Age < 14)]

PassengerId  Survived  Pclass                           Name     Sex  \
125          126         1       3   Nicola-Yarred, Master. Elias    male   
731          732         0       3       Hassan, Mr. Houssein G N    male   
777          778         1       3  Emanuel, Miss. Virginia Ethel  female   
780          781         1       3           Ayoub, Miss. Banoura  female   

      Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
125  12.0      1      0    2651  11.2417   NaN        C  
731  11.0      0      0    2699  18.7875   NaN        C  
777   5.0      0      0  364516  12.4750   NaN        S  
780  13.0      0      0    2687   7.2292   NaN        C

In [97]:
df[df.Name.str[:6] == 'Nicola']

PassengerId  Survived  Pclass                          Name     Sex  \
39            40         1       3   Nicola-Yarred, Miss. Jamila  female   
125          126         1       3  Nicola-Yarred, Master. Elias    male   

      Age  SibSp  Parch Ticket     Fare Cabin Embarked  
39   14.0      1      0   2651  11.2417   NaN        C  
125  12.0      1      0   2651  11.2417   NaN        C

In [185]:
test = df.copy()
len(test.Name.str.split(',', expand=True)[0].unique())

667

In [187]:
cleaned_df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Deck
0         0       3    male  22.0      1      0   7.2500  NaN
1         1       1  female  38.0      1      0  71.2833    C
2         1       3  female  26.0      0      0   7.9250  NaN
3         1       1  female  35.0      1      0  53.1000    C
4         0       3    male  35.0      0      0   8.0500  NaN

In [189]:
# Replace values
cleaned_df.Sex.replace('male', 0, inplace=True)
cleaned_df.Sex.replace('female', 1, inplace=True)
cleaned_df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Deck
0         0       3    0  22.0      1      0   7.2500  NaN
1         1       1    1  38.0      1      0  71.2833    C
2         1       3    1  26.0      0      0   7.9250  NaN
3         1       1    1  35.0      1      0  53.1000    C
4         0       3    0  35.0      0      0   8.0500  NaN

In [193]:
cleaned_df.Deck.unique()

array([nan, 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [208]:
# labelling encode
# if possible there is the sklearn label_encoder

# cleaned_df.Deck.replace(['T', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], [0, 1, 2, 3, 4, 5, 6, 7], inplace=True)
cleaned_df.Deck.unique()

array([nan,  3.,  5.,  7.,  4.,  1.,  2.,  6.,  0.])

In [259]:
# create a new column to show empty cells of Deck
cleaned_df['Deck_missing'] = cleaned_df.Deck.isnull().astype(int)

In [264]:
# Fill the empty cells of Deck
cleaned_df.Deck.fillna(9, inplace=True)
cleaned_df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Deck  Fare_missing  \
0         0       3    0  22.0      1      0   7.2500   9.0             0   
1         1       1    1  38.0      1      0  71.2833   3.0             0   
2         1       3    1  26.0      0      0   7.9250   9.0             0   
3         1       1    1  35.0      1      0  53.1000   3.0             0   
4         0       3    0  35.0      0      0   8.0500   9.0             0   

   Deck_missing  
0             1  
1             0  
2             1  
3             0  
4             1

(891, 10)